notifications:
  email:
    false

sudo: false

language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8-dev"

script:
  - "python setup.py bdist" # detect syntax errors by byte-compiling
  - "python setup.py build"

deploy:
  provider: pypi
  user: moxfyre
  password:
    secure: IUe0vzjHCYbnWkO4ErYFUoo7SJ/iCNdTboVQ03lSjOhnq2ya+T5kEzXmt8u88yBhA0Ba3EkcM4h4Tfnt5VTVmyyID3eoGgxyMAyBzkgfnT+vzmWSbabsEOR+ERDGfIsEbsr0wHwGdP8GJzYAG9g5D5ikMG5yStE7y2Bj0ckRf3A3MsW+/CGOQL5WbhT63vC2YNu/XuF0lp8XhDHvHPspZbW7/SxwqwbPu8FBCzjDep2Gu+owWf04RIke9wPK5pWCiV74WTEEB+FalZTsvorVWu2pku8d+VMxlmhA5PJQhwIiZbUxkA89Hb/usN/u42PFkcFXEeNutXmRUDaJlH1Wr9JZVz8tIAP1hWQ3B/6yAHIvP+nZIYr5zkXlcBSYKYe5gt/6twRByFF2t6dbJJH0mqrsGdCdxgSkQHs34UUfoxRrfYwMhL9/hBMVicAMO7yqcjo6MEK7P0Nra4USUjXo70q3qEYxu862r/FJ8UsG/nf8WrsAVnwitKThH5eY1hJIpbPTAg/jgpRTVmRYJ8nTgHahxvJkyHGwgD3MY0/9ocfjGMqI2Pup5nlfhnjNVBKEppoETi6TE/gUcd75h1VFxKny/Wn7HQMVwHlk+tsOFKD7mNrDY0kmc7fHSYRVwx88L458h4IoIATkKgwTa5f/B6opLEAMI6Omh+aVFblqwo0=
  on:
    tags: true
    repo: dlenski/vpn-slice
